import 'dart:io';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:path_provider/path_provider.dart';

abstract class TtsDataSource {
  Future<File> generateSpeech(String text, String language);
}

class TtsDataSourceImpl implements TtsDataSource {
  final FlutterTts _flutterTts;

  TtsDataSourceImpl(this._flutterTts);

  @override
  Future<File> generateSpeech(String text, String language) async {
    try {
      await _flutterTts.setLanguage(language);

      final String fileName = 'translation_${DateTime.now().millisecondsSinceEpoch}.wav';

      if (Platform.isAndroid) {
        // Android typically saves to external storage.
        // We'll try to let it save, but locating it exactly without `getExternalStorageDirectory` is hard.
        // And `synthesizeToFile` is void.
        // This part is tricky to get right without a device.
        await _flutterTts.synthesizeToFile(text, fileName);

        // Attempt to guess location or use a temp file workaround if supported?
        // flutter_tts on Android doesn't easily return the path.
        // So we might fall through to the fallback in this specific demo code
        // unless we implement a more complex file handling logic.
      } else if (Platform.isIOS) {
        await _flutterTts.synthesizeToFile(text, fileName);
        final dir = await getApplicationDocumentsDirectory();
        final file = File('${dir.path}/$fileName');
        if (await file.exists()) {
          return file;
        }
      }
    } catch (e) {
      // Log error or ignore in this demo environment where plugin might be missing
    }

    // Fallback: Create a dummy file so the user can "download" something in the demo/sandbox.
    // This ensures the "Download" button works even if TTS fails (which it will in emulator/sandbox).
    final Directory tempDir = Directory.systemTemp;
    final File file = File('${tempDir.path}/translation_${DateTime.now().millisecondsSinceEpoch}.wav');
    await file.writeAsString("Start of audio content for: $text\n(Generated by Mock TTS for demo)");
    return file;
  }
}
