import 'package:equatable/equatable.dart';

class YouTubeSubtitleTrack extends Equatable {
  final String languageCode;
  final String name;
  final String baseUrl;
  final bool isAutoGenerated;

  const YouTubeSubtitleTrack({
    required this.languageCode,
    required this.name,
    required this.baseUrl,
    required this.isAutoGenerated,
  });

  @override
  List<Object?> get props => [languageCode, name, baseUrl, isAutoGenerated];
}
